#!/bin/bash

   OP_NAME="My awesome script"
  OP_USAGE="awesome_script [options]"
OP_VERSION="1.0.0"

OP_OPTIONS=(
	# -SHORT_NAME[:ARGUMENT_NAME] (-|--LONGNAME) DEFAULT_VALUE DESCRIPTION
	
	-v:level --verbose 2     "Level of verbosity, from 0 (quiet) to 10 (drunk uncle)."
	-f       --flag    false "A flag... Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	-p:port  -         54321 "One with no long name"
)
. options-parse

# To access an option value, use ARGS:
echo "Verbosity: ${ARGS[op_verbose]} or ${ARGS[op_v]}"
echo "     Flag: ${ARGS[op_flag]} or ${ARGS[op_f]}"
echo "     Port: ${ARGS[op_p]}"